//
// Created by diana on 24/12/2019.
//

#ifndef RECURSIVITY_BACKTRACKING_PROBLEM_3_2_H
#define RECURSIVITY_BACKTRACKING_PROBLEM_3_2_H

void p_3_2();

#endif //RECURSIVITY_BACKTRACKING_PROBLEM_3_2_H
